INC_DIR = \
	-I ../shared_header \
	-I ../add_sub \
	-I ../cmsis

OUTPUT_DIR = ../../build/

CFLAG:=-g -mcpu=cortex-m3 -O2 -Wall -ffunction-sections -fdata-sections -mthumb
ASFLAG:=-mthumb -mcpu=cortex-m3
