INC_DIR = \
	-I ../shared_header \
	-I ../add_sub \
	-I ../cmsis \
	-I ../uart \
	-I ../delay

OUTPUT_DIR = ../../build/

CFLAG:=-g -mcpu=cortex-m3 -O2 -Wall -ffunction-sections -fdata-sections -mthumb
ASFLAG:=-mthumb -mcpu=cortex-m3

#STM32F103C8T6 is a medium density device!
DEFS:=-D STM32F10X_MD
